version: '3'
services:
  
  mysql:
    image: mysql
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=library

  wildfly:
    build:
      context: web
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "0.0.0.0:4320:8080"
      - "0.0.0.0:4321:9990"

